"""Added status index to notification table

Revision ID: a65e2d108460
Revises: 3dc4998b0330
Create Date: 2026-09-10 11:47:46.261879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65e2d108460'
down_revision: Union[str, Sequence[str], None] = '3dc4998b0330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_app_status', 'notifications', ['application_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_app_status', table_name='notifications')
    # ### end Alembic commands ###
